name: CI for Next.js in frontpage folder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Versi Node.js yang akan diuji

    steps:
    # Checkout kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Node.js dengan versi yang sesuai
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn" # Aktifkan cache untuk Yarn

    # Pindah ke folder frontpage sebelum menjalankan perintah
    - name: Change to frontpage directory
      working-directory: ./frontpage
      run: echo "Using frontpage folder as project root"

    # Install dependensi menggunakan Yarn
    - name: Install dependencies
      working-directory: ./frontpage
      run: yarn install --frozen-lockfile

    # Build proyek Next.js
    - name: Build project
      working-directory: ./frontpage
      run: yarn build

    # Jalankan tes (opsional, tambahkan jika ada script `test` di package.json)
    - name: Run tests
      working-directory: ./frontpage
      run: yarn test

    # (Opsional) Periksa format kode dengan lint
    - name: Run lint
      working-directory: ./frontpage
      run: yarn lint
