name: CI for Next.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Versi Node.js yang akan diuji

    steps:
    # Checkout kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Node.js dengan versi yang sesuai
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn" # Aktifkan cache untuk Yarn

    # Install dependensi menggunakan Yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # Build proyek Next.js
    - name: Build project
      run: yarn build

    # Jalankan tes (opsional, tambahkan jika Anda memiliki script `test` di package.json)
    - name: Run tests
      run: yarn test

    # (Opsional) Periksa format kode dengan lint
    - name: Run lint
      run: yarn lint
