name: CI for Next.js in frontpage folder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    # Checkout kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Node.js dengan versi yang sesuai
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"

    # Install dependensi menggunakan Yarn di folder frontpage
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ./frontpage

    # Build proyek Next.js di folder frontpage
    - name: Build project
      run: yarn build
      working-directory: ./frontpage

    # Jalankan tes (opsional)
    - name: Run tests
      run: yarn test
      working-directory: ./frontpage

    # (Opsional) Jalankan lint
    - name: Run lint
      run: yarn lint
      working-directory: ./frontpage
